import type { Contract, HistoricalQuote, Partner, Product, Quote } from "./types";

export const PRODUCTS: Product[] = [
  { id: "xdr-pro", name: "Cortex XDR Pro", sku: "CRTX-XDR-PRO", category: "Endpoint", unit: "seat", unitPrice: 78 },
  { id: "xsiam", name: "Cortex XSIAM Enterprise", sku: "XSIAM-ENT", category: "SOC", unit: "seat", unitPrice: 42 },
  { id: "prisma-cloud", name: "Prisma Cloud Enterprise", sku: "PRISMA-CL-ENT", category: "Cloud Security", unit: "seat", unitPrice: 95 },
  { id: "sase", name: "Prisma SASE Edge", sku: "PRISMA-SASE", category: "Network Security", unit: "seat", unitPrice: 64 },
  { id: "autofocus", name: "AutoFocus Threat Intel", sku: "ATF-TI", category: "Network Security", unit: "seat", unitPrice: 18 },
  { id: "u42-ir", name: "Unit 42 IR Retainer (40 hrs)", sku: "U42-IR-RET", category: "Services", unit: "retainer", unitPrice: 95000 },
  { id: "sup-247", name: "Premier Support 24×7", sku: "SUP-247", category: "Support", unit: "package", unitPrice: 48000 },
  { id: "svc-onb", name: "Onboarding & Deployment", sku: "SVC-ONB", category: "Services", unit: "package", unitPrice: 28000 },
];

export const PARTNERS: Partner[] = [
  { id: "p-helix", name: "Helix Cyber Partners", tier: "Platinum", accountOwner: "Maya Chen", region: "NA" },
  { id: "p-northwind", name: "Northwind Analytics", tier: "Gold", accountOwner: "Daniel Park", region: "EMEA" },
  { id: "p-orbital", name: "Orbital Media Networks", tier: "Platinum", accountOwner: "Daniel Park", region: "EMEA" },
  { id: "p-stratus", name: "Stratus Logistics", tier: "Gold", accountOwner: "Priya Shah", region: "APAC" },
  { id: "p-bluepeak", name: "Bluepeak Retail Group", tier: "Silver", accountOwner: "Maya Chen", region: "NA" },
];

// Roughly "today" is late Sep 2026 in the demo world.
export const HISTORICAL_QUOTES: HistoricalQuote[] = [
  {
    id: "Q-2025-1182",
    customer: "Helios Manufacturing Co.",
    region: "NA",
    channel: "Direct",
    termMonths: 36,
    approvedBy: "Priya Raman — VP Deal Desk",
    approvedDate: "2026-04-14",
    lines: [
      { id: "h1a", productId: "xdr-pro", qty: 275, discountPct: 24, termYears: 3 },
      { id: "h1b", productId: "xsiam", qty: 275, discountPct: 20, termYears: 3 },
      { id: "h1c", productId: "sup-247", qty: 1, discountPct: 12, termYears: 3 },
      { id: "h1d", productId: "svc-onb", qty: 1, discountPct: 0, termYears: 3 },
    ],
    rationale: [
      "Identical 4-SKU bundle (XDR + XSIAM + Premier + Onboarding)",
      "Seat count within 10% (275 vs 250)",
      "Discount stack within 2 pts of requested",
    ],
  },
  {
    id: "Q-2026-0044",
    customer: "Cobalt Logistics LLC",
    region: "NA",
    channel: "Direct",
    termMonths: 24,
    approvedBy: "Marcus Lee — Director, Deal Desk",
    approvedDate: "2026-06-09",
    lines: [
      { id: "h2a", productId: "xdr-pro", qty: 220, discountPct: 21, termYears: 2 },
      { id: "h2b", productId: "xsiam", qty: 220, discountPct: 18, termYears: 2 },
      { id: "h2c", productId: "sup-247", qty: 1, discountPct: 8, termYears: 2 },
    ],
    rationale: ["3 of 4 SKUs match (no Onboarding)", "Discount profile nearly identical", "Same region & channel"],
  },
  {
    id: "Q-2026-0107",
    customer: "Verdant Health Systems",
    region: "NA",
    channel: "Reseller",
    termMonths: 36,
    approvedBy: "Sasha Kim — Sr. Deal Desk Analyst",
    approvedDate: "2026-05-02",
    lines: [
      { id: "h3a", productId: "xdr-pro", qty: 300, discountPct: 26, termYears: 3 },
      { id: "h3b", productId: "xsiam", qty: 300, discountPct: 22, termYears: 3 },
      { id: "h3c", productId: "sup-247", qty: 1, discountPct: 15, termYears: 3 },
      { id: "h3d", productId: "svc-onb", qty: 1, discountPct: 5, termYears: 3 },
    ],
    rationale: ["Full bundle match (4/4 SKUs)", "Higher seat count (+20%)", "Discounts trend 3–4 pts deeper"],
  },
  {
    id: "Q-2026-0211",
    customer: "Northwind Energy Partners",
    region: "EMEA",
    channel: "Direct",
    termMonths: 36,
    approvedBy: "Élodie Marchand — Deal Desk Lead, EMEA",
    approvedDate: "2026-07-21",
    lines: [
      { id: "h4a", productId: "xdr-pro", qty: 240, discountPct: 23, termYears: 3 },
      { id: "h4b", productId: "xsiam", qty: 240, discountPct: 19, termYears: 3 },
      { id: "h4c", productId: "svc-onb", qty: 1, discountPct: 0, termYears: 3 },
    ],
    rationale: ["Core platform + XSIAM bundle matches", "Different region (EMEA) baseline", "No Premier Support"],
  },
  {
    id: "Q-2026-0288",
    customer: "Pacific Bay Retail Group",
    region: "APAC",
    channel: "Distributor",
    termMonths: 24,
    approvedBy: "Hiroshi Tanaka — Deal Desk Manager, APAC",
    approvedDate: "2026-08-18",
    lines: [
      { id: "h5a", productId: "xdr-pro", qty: 200, discountPct: 28, termYears: 2 },
      { id: "h5b", productId: "sup-247", qty: 1, discountPct: 18, termYears: 2 },
      { id: "h5c", productId: "svc-onb", qty: 1, discountPct: 10, termYears: 2 },
    ],
    rationale: ["Platform + support overlap, XSIAM missing", "Distributor channel pricing", "Different region (APAC)"],
  },
  {
    id: "Q-2026-0319",
    customer: "Halberd Insurance Group",
    region: "NA",
    channel: "Direct",
    termMonths: 36,
    approvedBy: "Priya Raman — VP Deal Desk",
    approvedDate: "2026-09-03",
    lines: [
      { id: "h6a", productId: "prisma-cloud", qty: 120, discountPct: 17, termYears: 3 },
      { id: "h6b", productId: "sase", qty: 4200, discountPct: 21, termYears: 3 },
      { id: "h6c", productId: "u42-ir", qty: 1, discountPct: 0, termYears: 3 },
    ],
    rationale: ["Cloud + SASE consolidation bundle", "IR retainer attach at list", "Different product mix"],
  },
];

export const INITIAL_QUOTES: Quote[] = [
  {
    id: "q-nimbus",
    number: "Q-2026-0814",
    customer: "Nimbus Robotics, Inc.",
    industry: "Manufacturing",
    region: "NA",
    channel: "Direct",
    partnerId: "p-helix",
    seats: 250,
    termYears: 3,
    owner: "Alex Chen",
    createdAt: Date.now() - 86_400_000 * 2,
    status: "draft",
    lines: [
      { id: "qn-1", productId: "xdr-pro", qty: 250, discountPct: 22, termYears: 3, source: "bundle" },
      { id: "qn-2", productId: "xsiam", qty: 250, discountPct: 18, termYears: 3, source: "bundle" },
      { id: "qn-3", productId: "sup-247", qty: 1, discountPct: 10, termYears: 3 },
      { id: "qn-4", productId: "svc-onb", qty: 1, discountPct: 0, termYears: 3 },
    ],
    audit: [
      { id: "a1", ts: Date.now() - 86_400_000 * 2, actor: "Seller", action: "Quote created from intake", detail: "250 seats · 3yr · NA · Direct" },
      { id: "a2", ts: Date.now() - 86_400_000 * 2 + 300_000, actor: "Copilot", action: "Bundle suggested", detail: "XDR Pro + XSIAM + Premier Support (91% confidence)" },
ed    ],
  },
  {
    id: "q-cobalt",
    number: "Q-2026-0821",
    customer: "Coastal Mutual Insurance",
    industry: "Financial Services",
    region: "NA",
    channel: "Reseller",
    partnerId: "p-bluepeak",
    seats: 1200,
    termYears: 3,
    owner: "Jordan Diaz",
    createdAt: Date.now() - 86_400_000 * 4,
    status: "submitted",
    submittedAt: Date.now() - 86_400_000,
    lines: [
      { id: "qc-1", productId: "prisma-cloud", qty: 140, discountPct: 19, termYears: 3 },
      { id: "qc-2", productId: "sase", qty: 1200, discountPct: 24, termYears: 3 },
      { id: "qc-3", productId: "u42-ir", qty: 1, discountPct: 5, termYears: 3 },
ec  ],
    audit: [
      { id: "a3", ts: Date.now() - 86_400_000 * 4, actor: "Seller", action: "Quote created from intake" },
      { id: "a4", ts: Date.now() - 86_400_000, actor: "Seller", action: "Submitted for approval", detail: "Blended discount 22.8% → VP Sales + Deal Desk" },
    ],
  },
];

export const INITIAL_CONTRACTS: Contract[] = [
  {
    id: "c-1001",
    number: "MSA-2024-1001",
    quoteId: "Q-2025-1182",
    customer: "Helios Manufacturing Co.",
    partnerId: "p-helix",
    startDate: "2024-10-01",
    endDate: "2027-09-30",
    status: "Active",
    autoRenew: true,
    notes: "3-year platform + XSIAM. XSIAM seats added mid-term in 2026, co-termed to MSA end.",
    lines: [
      { id: "cl-1a", productId: "xdr-pro", qty: 275, discountPct: 24, termYears: 3, startDate: "2024-10-01", endDate: "2027-09-30", source: "original" },
      { id: "cl-1b", productId: "xsiam", qty: 350, discountPct: 20, termYears: 3, startDate: "2026-04-01", endDate: "2027-09-30", source: "amendment" },
      { id: "cl-1c", productId: "sup-247", qty: 1, discountPct: 12, termYears: 3, startDate: "2024-10-01", endDate: "2027-09-30", source: "original" },
    ],
    amendments: [
      {
        id: "am-1",
        date: "2026-04-01",
        type: "add",
        description: "Added 350 Cortex XSIAM seats, co-termed to MSA end (prorated ~18 months).",
        deltaValue: 42 * 350 * 0.8 * 1.5,
        author: "Maya Chen",
      },
    ],
  },
  {
    id: "c-1002",
    number: "MSA-2023-1044",
    quoteId: "Q-2026-0044",
    customer: "Cobalt Logistics LLC",
    partnerId: "p-northwind",
    startDate: "2023-11-01",
    endDate: "2026-10-31",
    status: "Expiring",
    autoRenew: false,
    notes: "Renewal decision needed 30 days before end date. Partner requested co-term with their Helios resale agreement.",
    lines: [
      { id: "cl-2a", productId: "xdr-pro", qty: 220, discountPct: 21, termYears: 3, startDate: "2023-11-01", endDate: "2026-10-31", source: "original" },
      { id: "cl-2b", productId: "xsiam", qty: 220, discountPct: 18, termYears: 3, startDate: "2023-11-01", endDate: "2026-10-31", source: "original" },
      { id: "cl-2c", productId: "sup-247", qty: 1, discountPct: 8, termYears: 3, startDate: "2023-11-01", endDate: "2026-10-31", source: "original" },
    ],
    amendments: [],
  },
  {
    id: "c-1003",
    number: "MSA-2024-1078",
    customer: "Verdant Health Systems",
    partnerId: "p-orbital",
    startDate: "2024-01-15",
    endDate: "2027-01-14",
    status: "Active",
    autoRenew: true,
    notes: "Reseller channel via Orbital Media. QBR scheduled Nov 2026.",
    lines: [
      { id: "cl-3a", productId: "xdr-pro", qty: 300, discountPct: 26, termYears: 3, startDate: "2024-01-15", endDate: "2027-01-14", source: "original" },
      { id: "cl-3b", productId: "xsiam", qty: 300, discountPct: 22, termYears: 3, startDate: "2024-01-15", endDate: "2027-01-14", source: "original" },
      { id: "cl-3c", productId: "svc-onb", qty: 1, discountPct: 5, termYears: 3, startDate: "2024-01-15", endDate: "2025-01-14", source: "original" },
    ],
    amendments: [],
  },
  {
    id: "c-1004",
    number: "MSA-2022-0902",
    customer: "Pacific Bay Retail Group",
    partnerId: "p-stratus",
    startDate: "2022-09-01",
    endDate: "2025-08-31",
    status: "Expired",
    autoRenew: false,
    notes: "Expired without renewal. Win-back opportunity — new quote in progress.",
    lines: [
      { id: "cl-4a", productId: "xdr-pro", qty: 200, discountPct: 28, termYears: 3, startDate: "2022-09-01", endDate: "2025-08-31", source: "original" },
      { id: "cl-4b", productId: "sup-247", qty: 1, discountPct: 18, termYears: 3, startDate: "2022-09-01", endDate: "2025-08-31", source: "original" },
    ],
    amendments: [],
  },
];
