/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as QuotesQuoteIdRouteImport } from './routes/quotes._quoteId'
import { Route as QuotesNewRouteImport } from './routes/quotes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesQuoteIdRoute = QuotesQuoteIdRouteImport.update({
  id: '/_quoteId',
  getParentRoute: () => QuotesRoute,
} as any)
const QuotesNewRoute = QuotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => QuotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quotes': typeof QuotesRouteWithChildren
  '/quotes/_quoteId': typeof QuotesQuoteIdRoute
  '/quotes/new': typeof QuotesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quotes' | '/quotes/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quotes' | '/quotes/new'
  id: '__root__' | '/' | '/quotes' | '/quotes/_quoteId' | '/quotes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuotesRoute: typeof QuotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes/_quoteId': {
      id: '/quotes/_quoteId'
      path: ''
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesQuoteIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/quotes/new': {
      id: '/quotes/new'
      path: '/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof QuotesNewRouteImport
      parentRoute: typeof QuotesRoute
    }
  }
}

interface QuotesRouteChildren {
  QuotesQuoteIdRoute: typeof QuotesQuoteIdRoute
  QuotesNewRoute: typeof QuotesNewRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesQuoteIdRoute: QuotesQuoteIdRoute,
  QuotesNewRoute: QuotesNewRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuotesRoute: QuotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
